version: '3.4'

services:
  worktimetracker.mvc:
    image: ${DOCKER_REGISTRY-}worktimetrackermvc
    build:
      context: .
      dockerfile: src/WorkTimeTracker.MVC/Dockerfile
  db:
    container_name: WorkTimeTrackerDb
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      SA_PASSWORD: "Strong@Passw0rd"
      ACCEPT_EULA: "Y"